# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database

postgres_default: &postgres_default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: postgres
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 54322 } %>

sqlite_default: &sqlite_default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *postgres_default
  cache:
    <<: *sqlite_default
    database: storage/cache_development.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite_default
    database: storage/queue_development.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite_default
    database: storage/cable_development.sqlite3
    migrations_paths: db/cable_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *postgres_default
    database: bento_manager_test
  cable:
    <<: *sqlite_default
    database: storage/cable_test.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *postgres_default
  cache:
    <<: *sqlite_default
    database: storage/cache_production.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite_default
    database: storage/queue_production.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite_default
    database: storage/cable_production.sqlite3
    migrations_paths: db/cable_migrate
